### ISSUE TITLE
casatables - Returned strings are malformed

### ISSUE THREAD

**Issue by cjordan** [pkgw/rubbl#133]
More precisely, if asking for a single string from a measurement set, it always seems to be garbage, or if asking for many strings, the first one is garbage *sometimes*.

I've tried to fix this on my own without success. I'm wondering if you have some additional knowledge that might help. However, I'm suspicious of this code:

https://github.com/pkgw/rubbl/blob/6b07da175384f3f73f571b5972a5e53aea63b463/casatables/src/lib.rs#L339-L345

The `as_ptr` documentation for `str` says: The caller must ensure that the returned pointer is never written to. If you need to mutate the contents of the string slice, use as_mut_ptr.

So, I suspect that this code is currently UB. At this point inside `get_cell`

https://github.com/pkgw/rubbl/blob/6b07da175384f3f73f571b5972a5e53aea63b463/casatables/src/lib.rs#L728

I tried calling a new method (`from_rust2`) with a mutable `Vec<u8>`, but that didn't seem to help (although I'm not sure how C++ strings work compared to C strings).

Here's a small measurement set, and following is some code to expose the issue: [1118529192_8s_160kHz_stripped.ms.tar.gz](https://github.com/pkgw/rubbl/files/5685241/1118529192_8s_160kHz_stripped.ms.tar.gz)

```rust
use rubbl_casatables::{Table, TableOpenMode};

fn main() {
    let ms = std::env::args()
        .skip(1)
        .next()
        .expect("No measurement set supplied");

    let mut t = Table::open(&format!("{}/ANTENNA", ms), TableOpenMode::Read).unwrap();
    let col = "NAME";

    let names: Vec<String> = t.get_col_as_vec(col).unwrap();
    println!("{:?}", &names[0..3]);

    let first_name: String = t.get_cell(col, 0).unwrap();
    dbg!(first_name);

    let second_name: String = t.get_cell(col, 1).unwrap();
    dbg!(second_name);
}
```

Example output (the first line is correct):
```
["Tile011", "Tile012", "Tile013"]
[src/main.rs:16] first_name = "\u{1a}ZsU\u{0}"
[src/main.rs:19] second_name = "p\u{ecd5}\u{0}"
```

**Comment by pkgw** [comment]
I can reproduce the problem with your test case — thanks for putting one together!

I certainly am not super happy about the string bridge code, but I think the part that you pointed out should be OK. The result of `as_ptr()` isn't written to — instead that pointer is replaced with something CASA-owned.

I'm tracking this down in the debugger and the problem seems to be in `StringBridge::to_rust()`:

```rust
    fn to_rust(&self) -> String {
        let buf = unsafe { std::slice::from_raw_parts(self.data as *const u8, self.n_bytes as usize) };
        // buf is OK here
        String::from_utf8_lossy(buf).into_owned()
        // the data in buf are now garbage here
    }
```

I'm thinking that maybe the issue relates to [this caveat](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#caveat), and that the compiler is somehow deciding that it owns the slice contents and can trash them.

**Comment by pkgw** [comment]
Ah, no. We are ending up with illegal aliasing. In the calls to `StringBridge::to_rust()` that succeed, there is an %rsp register that is different than the `self` buffer: 

```
(gdb) p/x $rsp
$79 = 0x7fffffffcea0
(gdb) p *self
$80 = rubbl_casatables::glue::StringBridge {data: 0x555555a08370, n_bytes: 7}
```

In the calls that fail, these pointers are aliased to each other:

```
(gdb) p/x $rsp
$83 = 0x7fffffffcf80
(gdb) p *self
$84 = rubbl_casatables::glue::StringBridge {data: 0x7fffffffcf80, n_bytes: 7}
```

The other suspicious thing is that in the failing call, the StringBridge buffer is in the stack (`rsp` is the stack pointer), whereas it's in a totally different memory region for the calls that succeed ... but it seems like too much of a coincidence that `rsp` ends up being *exactly* `self.data`.

**Comment by pkgw** [comment]
Eh, never mind, now I think it *is* just a coincidence.

The fundamental problem is the one that I've always been struggling with, transmitting memory across the C++/Rust boundary. This particular codepath essentially involves passing a pointer across this boundary and that just can't work reliably unless the pointer is into a long-lived memory allocation. In this case, the scalar `get_call()` call yields a stack-allocated C++ string object, and the string's contents are short such that the small-string optimization is applied, so that the string buffer is also on the stack. After the C++ code returns, the Rust code steps on those data. So the buffer isn't actually invalid as soon as the C++ returns, but as long as it's stack-allocated there's no way to ensure that it stays valid.

The only way for such a pattern to work reliably is to use a callback, as seen in glue functions like `table_get_column_names()`. So, I'll add one.

**Comment by cjordan** [comment]
Thanks for jumping on this so enthusiastically! Glad I didn't spin my wheels too hard -- I've done some FFI with Rust, but not with C++.

In case it helps, I think there are one or two C++ interop crates, but I've never used them.

**Comment by pkgw** [comment]
Well, when you work in Rust it's pretty bad form to deliver code with memory safety issues! I have a proof of concept that seems to fix the error in your example. I'll tidy up the rest tomorrow.

**Comment by cjordan** [comment]
Thanks again! Don't feel too bad - FFI is "lowering yourself" to C/C++'s level, and these kind of problems should remind us why we want to move away from them (in most cases)...

**Comment by pkgw** [comment]
I think #134 will solve this.

**Comment by pkgw** [comment]
I'm in the process of releasing version 0.2 of the crate, which should deploy this fix.

**Comment by pkgw** [comment]
Oops, it took a couple of iterations to get the release automation fully working … but now there should be a 0.2.2 on Crates.io with the fix.

**Comment by cjordan** [comment]
Well, that looked frustrating!  But, thanks very much for your persistence. It appears to have been worth it:

```
["Tile011", "Tile012", "Tile013"]
[src/main.rs:16] first_name = "Tile011"
[src/main.rs:19] second_name = "Tile012"
```

Thanks again!

BTW, depending on how I'm going for time, soon I might start trying to convert your libraries from `failure` to `thiserror`.

**Comment by pkgw** [comment]
@cjordan Nothing too bad, just a bit of bootstrapping to do since I had only published a subset of the crates to Cargo before. Fixing that is a bit more tedious in the automation scenario but am I *loving* how [Cranko](https://pkgw.github.io/cranko/) is changing my release workflow, especially for monorepos such as this.

I will certainly be happy to accept any work that you can do to improve the error handling!
